### ISSUE TITLE
zxcvbn is not defined

### ISSUE THREAD

**Issue by madavik** [codetheweb/zxcvbn#1]
I am getting the error zxcvbn is not defined after upgrading to meteor 1.3.

**Comment by codetheweb** [comment]
@madavik Sorry about that.  I haven't updated this package in a while.  @lowe should probably just remove it from the list of 'official' packages for zxcvbn.  In 1.3, Meteor supports easily [using NPM packages](http://info.meteor.com/blog/announcing-meteor-1.3), so that would be the best way going forward.

**Comment by madavik** [comment]
No worries. Yeah, I ended up using the npm package. Thanks
